Client/Controllers/EventController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers;

[Authorize(Roles = "Admin,Event Organizer")]
public class EventController : Controller
{
    public EventController()
    {
    }

    [AllowAnonymous]
    public IActionResult Index()
    {
        return View();
    }

    [AllowAnonymous]
    public IActionResult Create()
    {
        return View();
    }

    [Route("/Event/D/{slug}")]
    [AllowAnonymous]
    public IActionResult DetailEvent()
    {
        return View();
    }

    [Authorize(Roles = "Event Organizer")]
    public IActionResult Manage()
    {
        return View();
    }

    [Authorize(Roles = "Event Organizer")]
    public IActionResult Dashboard()
    {
        return View();
    }

    [Authorize(Roles = "Event Organizer")]
    public IActionResult Order()
    {
        return View();
    }

    [Authorize(Roles = "Event Organizer")]
    public IActionResult OrderTicket()
    {
        return View();
    }

    [Authorize(Roles = "Event Organizer")]
    public IActionResult Revenue()
    {
        return View();
    }

    [Authorize(Roles = "Admin")]
    public IActionResult List()
    {
        return View();
    }

    [Route("/Event/Detail/{id}")]
    public IActionResult Detail()
    {
        return View();
    }

    [Route("/Event/Attendees/{id}")]
    public IActionResult Attendee()
	{
		return View();
	}
}

Client/Controllers/OrderController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers;

[Authorize(Roles = "User")]
public class OrderController : Controller
{
	public OrderController()
	{
	}

    [Route("/Order/Invoice/{transactionId}")]
    [Authorize(Roles = "User")]
    public IActionResult Index()
    {
        return View();
    }

    [Route("/Booking/{transactionId}")]
    [Authorize(Roles = "User")]
    public IActionResult Booking()
	{
		return View();
	}

    [Route("/Pay/{transactionId}")]
    [Authorize(Roles = "User")]
    public IActionResult Payment()
	{
		return View();
	}

    [Authorize(Roles = "User")]
    public IActionResult Cancel()
	{
		return View();
	}

    [Route("/Order/Success/{transactionId}")]
    [Authorize(Roles = "User")]
    public IActionResult Success()
	{
		return View();
	}

    [Authorize(Roles = "User")]
    public IActionResult MyTicket()
	{
		return View();
	}

    [Route("/Order/Invoice/Print/{transactionId}")]
    [Authorize(Roles = "User")]
    public IActionResult Print()
    {
        return View();
    }
}

Client/Controllers/PaymentController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers;

[Authorize(Roles = "Event Organizer")]
public class PaymentController : Controller
{
    public PaymentController()
    {
    }

    public IActionResult Approve()
    {
        return View();
    }
}

Client/Controllers/UserController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers;

[Authorize(Roles = "Admin,User,Event Organizer")]
public class UserController : Controller
{
	public UserController()
	{
	}

    [Authorize(Roles = "User,Event Organizer")]
	public IActionResult Profile()
	{
		return View();
	}

    [Authorize(Roles = "User,Event Organizer")]
	public IActionResult ChangePassword()
    {
        return View();
    }

    [Authorize(Roles = "Admin")]
	public IActionResult List()
	{
		return View();
	}

    [Authorize(Roles = "Admin")]
	public IActionResult Create()
	{
		return View();
	}
}

Client/Views/Shared/_Partials/_HeroUser.cshtml
<section class="page-title page-title-bottom bg-holder bg-overlay-black-50">
    <div class="container">
        <div class="row align-items-center position-relative">
            <div class="col-lg-6">
                <div class="d-flex align-items-center">
                    <img class="img-fluid rounded-circle avatar avatar-xll" src="" alt="User Picture" id="hero_user_picture">
                    <div class="ms-4">
                        <h3 class="text-white mb-2" id="hero_user_name"></h3>
                        <div class="d-flex">
                            <span class="d-inline-block text-white">The first thing to remember about success.</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Client/Views/Shared/_Partials/_Sidebar.cshtml
<div class="widget">
    <div class="widget-title">
        <h6> <i class="fas fa-home"></i> Main </h6>
    </div>
    <div class="widget-content dashboard-nav">
        <ul class="list-unstyled">
            <!-- <li><a href="dashboard.html"> <i class="fas fa-home me-2"></i> Dashboard</a></li> -->
            <li><a class="" is-active-route asp-area="" asp-controller="User" asp-action="Profile"> <i class="fas fa-user me-2"></i> My Profile</a></li>
            <li><a class="" is-active-route asp-area="" asp-controller="User" asp-action="ChangePassword"> <i class="fas fa-key me-2"></i> Password</a></li>
        </ul>
        <h5 class="mb-4 mt-5">Other</h5>
        <ul class="list-unstyled">
            <li><a class="d-none user_menu" is-active-route asp-area="" asp-controller="Order" asp-action="MyTicket"> <i class="fas fa-list-ul me-2"></i> My Tickets</a></li>
            <li><a class="d-none event_organizer_menu" is-active-route asp-area="" asp-controller="Payment" asp-action="Approve"> <i class="far fa-calendar-alt me-2"></i> Approval Payments</a></li>
            <li><a class="d-none event_organizer_menu" is-active-route asp-area="" asp-controller="Event" asp-action="Manage"> <i class="fas fa-clock me-2"></i> Manage Events</a></li>
            <li><a class="d-none event_organizer_menu" is-active-route asp-area="" asp-controller="Organizer" asp-action="Manage"> <i class="far fa-building me-2"></i> Manage Organizer</a></li>
        </ul>
        <a class="btn btn-secondary btn-sm mt-2"  asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
    </div>
</div>

Client/Views/Shared/_Partials/_SidebarEvent.cshtml
<div class="widget">
    <div class="widget-content dashboard-nav">
        <ul class="list-unstyled">
            <li><a class="sidebar-net-dashboard" is-active-route asp-area="" asp-controller="Event" asp-action="Dashboard"> Events Dashboard</a></li>
            <li><a class="sidebar-net-order" is-active-route asp-area="" asp-controller="Event" asp-action="Order"> Events Order</a></li>
            <li><a class="sidebar-net-revenue" is-active-route asp-area="" asp-controller="Event" asp-action="Revenue"> Revenue Earned</a></li>
            <li><a class="sidebar-net-ticket" is-active-route asp-area="" asp-controller="Event" asp-action="OrderTicket"> Events Order Tickets</a></li>
        </ul>
        <div class="d-grid gap-2">
            <button type="button" class="btn btn-secondary btn-sm mt-2" id="print_attendees">Download Attendee List</button>
        </div>
    </div>
</div>